name: Build Microcluster

on:
  workflow_call:

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-canonical-dev -y
      - name: Build binary
        working-directory: ./sunbeam-microcluster
        run: make build
