name: Test Microcluster

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-canonical-dev -y
      - name: Run linters
        working-directory: ./sunbeam-microcluster
        run: make check-static

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:dqlite/dev
          sudo apt install build-essential dqlite-tools libdqlite-dev libraft-canonical-dev -y
      - name: Run tests
        working-directory: ./sunbeam-microcluster
        run: make check-unit


